version: '3.8'

services:
  mongo:
    image: mongo
    container_name: collab_mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  
  redis:
    image: redis
    container_name: collab_redis
    ports:
      - 6379:6379